- ชื่อ: ตั้งค่า Java JDK

  ใช้: การดำเนินการ/setup-java@v3.12.0

  กับ:

    # เวอร์ชัน Java เพื่อตั้งค่า ใช้เวอร์ชัน Java ทั้งหมดหรือบางส่วน ดูตัวอย่างไวยากรณ์ที่รองรับในไฟล์ README

    รุ่น Java: # ตัวเลือก

    # เส้นทางไปยังไฟล์ `.java-version` ดูตัวอย่างไวยากรณ์ที่รองรับในไฟล์ README

    ไฟล์เวอร์ชัน Java: # ตัวเลือก

    # การกระจาย Java ดูรายการการกระจายที่รองรับในไฟล์ README

    การกระจาย:

    # ประเภทแพ็คเกจ (jdk, jre, jdk+fx, jre+fx)

    java-package: # ตัวเลือก ค่าเริ่มต้นคือ jdk

    # สถาปัตยกรรมของแพ็คเกจ (ค่าเริ่มต้นคือสถาปัตยกรรมของแอคชั่นรันเนอร์)

    สถาปัตยกรรม: # ตัวเลือก

    # พาธไปยังตำแหน่งของ JDK ที่บีบอัด

    jdkFile: # ตัวเลือก

    # ตั้งค่าตัวเลือกนี้หากคุณต้องการให้การดำเนินการตรวจสอบเวอร์ชันล่าสุดที่มีอยู่ซึ่งตรงตามข้อกำหนดของเวอร์ชัน

    ตรวจสอบล่าสุด: # ตัวเลือก

    # ID ของที่เก็บ distributionManagement ในไฟล์ pom.xml ค่าเริ่มต้นคือ `github`

    รหัสเซิร์ฟเวอร์: # ตัวเลือก ค่าเริ่มต้นคือ GitHub

    # ชื่อตัวแปรสภาพแวดล้อมสำหรับชื่อผู้ใช้สำหรับการตรวจสอบสิทธิ์ไปยังที่เก็บ Apache Maven ค่าเริ่มต้นคือ $GITHUB_ACTOR

    ชื่อผู้ใช้เซิร์ฟเวอร์: # ไม่บังคับ ค่าเริ่มต้นคือ GITHUB_ACTOR

    # ชื่อตัวแปรสภาพแวดล้อมสำหรับรหัสผ่านหรือโทเค็นสำหรับการตรวจสอบสิทธิ์ไปยังที่เก็บ Apache Maven ค่าเริ่มต้นคือ $GITHUB_TOKEN

    รหัสผ่านเซิร์ฟเวอร์: # ไม่บังคับ ค่าเริ่มต้นคือ GITHUB_TOKEN

    # พาธไปยังตำแหน่งที่จะเขียนไฟล์ settings.xml ค่าเริ่มต้นคือ ~/.m2

    เส้นทางการตั้งค่า: # ตัวเลือก

    # เขียนทับไฟล์ settings.xml หากมีอยู่ ค่าเริ่มต้นคือ "จริง"

    การตั้งค่าการเขียนทับ: # ไม่บังคับ ค่าเริ่มต้นคือจริง

    # รหัสส่วนตัว GPG เพื่อนำเข้า เริ่มต้นคือสตริงว่าง

    gpg-private-key: # ตัวเลือก

    # ชื่อตัวแปรสภาพแวดล้อมสำหรับวลีรหัสผ่านคีย์ส่วนตัวของ GPG ค่าเริ่มต้นคือ $GPG_PASSPHRASE

    gpg-passphrase: # ตัวเลือก

    # ชื่อของแพลตฟอร์มการสร้างเพื่อแคชการอ้างอิง อาจเป็น "maven", "gradle" หรือ "sbt"

    แคช: # ตัวเลือก

    # วิธีแก้ปัญหาเพื่อผ่านสถานะงานเพื่อโพสต์ขั้นตอนงาน ตัวแปรนี้ไม่ได้มีไว้สำหรับการตั้งค่าด้วยตนเอง

    สถานะงาน: # ไม่บังคับ ค่าเริ่มต้นคือ ${{ job.status }}

    # โทเค็นที่ใช้ในการตรวจสอบความถูกต้องเมื่อดึงรายการเวอร์ชันที่โฮสต์บน github.com เช่น Microsoft Build ของ OpenJDK เมื่อเรียกใช้การดำเนินการนี้บน github.com ค่าเริ่มต้นก็เพียงพอแล้ว เมื่อทำงานบน GHES คุณสามารถส่งโทเค็นการเข้าถึงส่วนบุคคลสำหรับ github.com ได้ หากคุณประสบกับอัตราที่จำกัด

    โทเค็น: # ไม่บังคับ ค่าเริ่มต้นคือ ${{ github.server_url == 'https://github.com' && github.token || '' }}

    # ชื่อของรหัส Maven Toolchain หากไม่ต้องการชื่อเริ่มต้นของ "${distribution}_${java-version}" ดูตัวอย่างไวยากรณ์ที่รองรับในไฟล์การใช้งานขั้นสูง

    mvn-toolchain-id: # ตัวเลือก

    # ชื่อของ Maven Toolchain Vendor หากไม่ต้องการชื่อเริ่มต้นของ "${distribution}" ดูตัวอย่างไวยากรณ์ที่รองรับในไฟล์การใช้งานขั้นสูง

    mvn-toolchain-vendor: # ตัวเลือก...
...
